apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.service.name | quote }}
  labels:
    {{- include "migrations-helm-staging.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "migrations-helm-staging.selectorLabels" . | nindent 4 }}
   