apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:  
    {{- include "transferservice-helm-staging.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels: 
      {{- include "transferservice-helm-staging.selectorLabels" . | nindent 6 }}
  template:
    metadata: 
      labels:
        {{- include "transferservice-helm-staging.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.existingSecret }}
         
          ports:
            - containerPort: {{ .Values.service.targetport }}
    