apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.service.name | quote }}
  labels:
    {{- include "transferservice-helm-staging.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      name: "http"
  selector:
    {{- include "transferservice-helm-staging.selectorLabels" . | nindent 4 }}
   